### ISSUE TITLE
GET /bills – Grab current pending bills

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-api#1]
We need an API to display the current bills for federal, state, and local level.

**Comment by dsernst** [comment]
@rdixit and I began looking at this. Here's an API for congressional bills: https://www.govtrack.us/api/v2/bill?congress=112&order_by=-current_status_date

**Comment by dsernst** [comment]
Here's San Francisco's Board of Supervisors site where they publish legislation as it gets introduced (pdf): http://www.sfbos.org/index.aspx?page=18701

**Comment by dsernst** [comment]
Looks like https://sunlightlabs.github.io/openstates-api/bills.html#bill-fields will work as an API for California bills.

**Comment by jaredscheib** [comment]
Super cool - great finds!
