### ISSUE TITLE
Mailgun may not be right long-term

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-api#16]
Mailgun may not be reliable for the long-term . [API docs haven't been touched in 2 years](https://github.com/mailgun/documentation). They were acquired by Rackspace in 2012. Rackspace was acquired by Apollo Global Management recently.

We need a better solution long-term.

**Comment by jaredscheib** [comment]
This is a great question for the community, to hear the thoughts of how people feel about this.

**Comment by dsernst** [comment]
What is the question?

**Comment by jaredscheib** [comment]
How do people feel about that ownership, that security concern, and what action we should take about it?
