### ISSUE TITLE
PUT /voters/:voter_id

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-api#8]
# POST /voters

An API endpoint to create a new user in the system.

Expects:
```
body
{
  full_name: String <1 – 100 characters>,
  email: String, email regex, <1 - 200 characters>,
  zip: number, 0 < x < 99999,
  
  // also accepts the optional questions
  smartphone: String
  referral: String
  comments: String
}
```

**Comment by dsernst** [comment]
Removing priority label on this since http://join.liquiddemocracy.party works in the meantime, and #10 is more urgent for user flow.

**Comment by jaredscheib** [comment]
Could POST /users be more RESTful?

**Comment by dsernst** [comment]
Closed by https://github.com/liquidvote/liquid-api/commit/75fc01cdc9c0084520db5deea37545c3b7384db5. Note this endpoint was changed to:

```
// PUT /voters — An API endpoint to update voter registration info.
//
// Expects:
//
// body
// {
//   full_name: String <1 – 100 characters>,
//   zip: String, 00000 < x < 99999,
// }
```
