### ISSUE TITLE
Choice of database software?

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-api#9]
Nominate your favorite persistence layer

**Comment by dsernst** [comment]
My first instinct is [RethinkDB](https://www.rethinkdb.com/) or [AWS' DynamoDB](https://aws.amazon.com/dynamodb/).

**Comment by jaredscheib** [comment]
I don't have an opinion, but let's keep in mind that we may ultimately want a graph solution. It'll be interesting to learn how something like RethinkDB, which looks outstanding and I have a positive impression for, holds up as the network scales. I'd vote RethinkDB for now, NASA-approved.

**Comment by dsernst** [comment]
I've created a hosted RethinkDB instance through [Compose.io](https://www.compose.com/rethinkdb). The first 30 days are free, and then it's $22.50/month for first gb, $15/gb/month after that.
